---
# from https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml
version: 1.0.1
name: docker-policies
displayName: OPA Conftest Docker Policies
createdAt: 2021-09-10T21:27:55.549418+00:00
description: OPA Conftest policies enforcing security standards against Dockerfiles.
readme: |
  OPA Conftest policies enforcing security standards against Dockerfiles.
  
  The following policies are defined:

  - `CTNRSEC-0001`: Dockerfiles Must Pull From An Approved Private Registry
  - `CTNRSEC-0002`: Dockerfiles Should Not Use Environment Variables For Sensitive Values
install: |
  `conftest pull git::https://github.com/rallyhealth/conftest-policy-packs.git//policies`

  And configure your org-specific `--data` as necessary from [data/](https://github.com/rallyhealth/conftest-policy-packs/tree/main/data),
homeURL: https://rallyhealth.github.io/conftest-policy-packs/
keywords:
  - opa
  - conftest
  - docker
license: MIT
provider:
  name: Rally Health
