name: Conftest CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Test Rego Policies'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    container: openpolicyagent/conftest:v0.25.0

    steps:
      - uses: actions/checkout@v2.3.4

      - name: 'Install Dependencies'
        run: apk add --no-cache make

      - name: 'Conftest Verify'
        run: make test

  lint:
    name: 'Pre-Commit Checks'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4

      # Pre-req for the pre-commit action
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16'

      # If the version of konstraint updates during the lifetime of an open PR, the
      # caching benefits will disappear.
      # In the general case, this cuts ~3 minutes from this job.
      - name: 'Cache Go'
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/
          key: ${{ runner.os }}-go-${{ github.head_ref }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 'Install Dependencies'
        run: |
          brew install conftest
          go install github.com/plexsystems/konstraint@latest

      - name: 'Pre-Commit Checks'
        uses: pre-commit/action@v2.0.3
