name: Conftest CI

on:
  pull_request:
    branches:
      - main

env:
  CONFTEST_VERSION: 0.25.0

jobs:
  test:
    name: 'Test Rego Policies'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    container: openpolicyagent/conftest:v${{ env.CONFTEST_VERSION }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: 'Conftest Verify'
        run: |
          apk add --no-cache make
          make test

  lint:
    name: 'Pre-Commit Checks'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    container: openpolicyagent/conftest:v${{ env.CONFTEST_VERSION }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 'Set up Node for local act'
        run: apk add --no-cache nodejs npm
        # Only run on local workstation
        if: ${{ env.ACT }}

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16'

      - name: 'Install Dependencies'
        run: |
          pip install pre-commit
          make ci-install

      - name: 'Pre-Commit Checks'
        run: pre-commit run -a
