name: Conftest CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Pre-Commit Checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      # Pre-req for the pre-commit action
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - uses: actions/setup-go@v3.3.1
        with:
          go-version: '^1.16'
      
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # If the version of konstraint updates during the lifetime of an open PR, the
      # caching benefits will disappear.
      # In the general case, this cuts ~3 minutes from this job.
      - name: 'Cache Go'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/
          key: ${{ runner.os }}-go-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 'Install Dependencies'
        run: |
          brew install conftest
          ./scripts/ci-go-deps.sh

      - name: 'Pre-Commit Checks'
        uses: pre-commit/action@v2.0.3

      - name: "Ensure data files are correct file type"
        run: |
          # This will exit 1 if any files are found with a different file extension
          if [[ $(find ./data -maxdepth 1 -type f -not -name "*.yml") != "" ]];
          then
              echo "::error::Some files in data/ do not have .yml extensions"
              exit 1
          fi
